version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: p1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" 
    networks:
      - backend-net

  backend:
    build: .
    container_name: spring-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - backend-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/p1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080

networks:
  backend-net:
